openapi: 3.0.0
info:
  title: Premier League API
  description:
    This API provides historical and analyze Premier League data between 2016 and 2019
  version: 2.0.0
servers:
  - url: /premier-api
paths:
  /team:
    get:
      summary: return a list of all team following by teamId,teamName,teamLogo
      operationId: controller.get_team
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
  /teamById/{teamId}:
    parameters:
    - name: teamId
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns a specific team by id.￼
      operationId: controller.get_team_by_id
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Team'
  /teamByArrayId/{teamId}:
    parameters:
    - name: teamId
      in: path
      required: true
      schema:
        type : array
        items:
          type: integer
    get:
      summary: return a list of specific team by id.
      operationId: controller.get_team_by_array_id
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
  /teamBySeason/{seasonId}:
    parameters:
    - name: seasonId
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns 20 team of premier league that have all ranking.
      operationId: controller.get_team_by_season
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamBySeason'
  /shotOnGoalAverageBySeason/{seasonId}:
    parameters:
    - name: seasonId
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns a list of average shot on goal for each team by the season.
      operationId: controller.get_shot_on_goal_by_season
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamShotOnGoalBySeason'
  /ballPossessionAverageBySeason/{seasonId}:
    parameters:
    - name: seasonId
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns a list of average ball possession for each team by the season.
      operationId: controller.get_ball_possession_by_season
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamBallPossessionBySeason'
  /foulsAverageBySeason/{seasonId}:
    parameters:
    - name: seasonId
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns a list of average fouls for each team by the season.
      operationId: controller.get_fouls_by_season
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamFoulsBySeason'
  /goalKeeperSavesAverageBySeason/{seasonId}:
    parameters:
    - name: seasonId
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns a list of average saves by goal keeper of each team.
      operationId: controller.get_goal_keeper_saves_by_season
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamGoalKeeperSavesBySeason'
  /blockedShotsAverageBySeason/{seasonId}:
    parameters:
    - name: seasonId
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns a list of average saves by goal keeper of each team.
      operationId: controller.get_blocked_shots_by_season
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamBlockedShotsBySeason'
  /passBallAverageBySeason/{seasonId}:
    parameters:
    - name: seasonId
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns a list of average total passes ball and average pass ball success of each team in select season.
      operationId: controller.get_total_passes_and_pass_accurate_by_season
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamPassBallBySeason'
    
components:
  schemas:
    Team:
      type: object
      properties:
        teamId:
          type: integer
        teamName:
          type: string
        teamLogo:
          type: string
    TeamBySeason:
      type: object
      properties:
        ranking:
          type: integer
        teamId:
          type: integer
        teamName:
          type: string
        teamLogo:
          type: string
          description: link of logo
        win:
          type: integer
        loss:
          type: integer
        draw:
          type: integer
        goalsDiff:
          type: integer
        points:
          type: integer
    TeamShotOnGoalBySeason:
      type: object
      properties:
        teamId:
          type: integer
        teamName:
          type: string
        teamLogo:
          type: string
        overallShotOnGoal:
          type: number
    TeamBallPossessionBySeason:
      type: object
      properties:
        teamId:
          type: integer
        teamName:
          type: string
        teamLogo:
          type: string
        overallBallPossession:
          type: number
    TeamFoulsBySeason:
      type: object
      properties:
        teamId:
          type: integer
        teamName:
          type: string
        teamLogo:
          type: string
        overallFouls:
          type: number
    TeamGoalKeeperSavesBySeason:
      type: object
      properties:
        teamId:
          type: integer
        teamName:
          type: string
        teamLogo:
          type: string
        overallTeamGoalKeeperBySeason:
          type: number
    TeamBlockedShotsBySeason:
      type: object
      properties:
        teamId:
          type: integer
        teamName:
          type: string
        teamLogo:
          type: string
        overallBlockedShotsBySeason:
          type: number
    TeamPassBallBySeason:
      type: object
      properties:
        teamId:
          type: integer
        teamName:
          type: string
        teamLogo:
          type: string
        overallTotalPasses:
          type: number
        overallPassAccurate:
          type: number

